### ISSUE TITLE
panic on `blocksync.(*SyncManager).onBlocksResponse`

### ISSUE THREAD

**Issue by xiaocong** [BOXFoundation/boxd#156]
```
INFO[0005] Block 9e2ad54184cd81688f07d67afed96bd8354f6d549c88f908fde79bd53cb6e45e connects to main chain  source="txpool/transaction_pool.go:132" tag=txpool
INFO[0005] Block ad10c81d47cbc52425db217973981790ce220c1ee504598a1018b615e81a9a63 connects to main chain  source="txpool/transaction_pool.go:132" tag=txpool
DEBU[0005] UTXO: apply block with 1 transactions         source="chain/utxoset.go:95" tag=chain
DEBU[0005] UTXO: apply block with 1 transactions         source="chain/utxoset.go:95" tag=chain
INFO[0005] Block a530576cc57321e5e85405ffbdf5dd3bd97890d08bb5e0f8854927057270ebae connects to main chain  source="txpool/transaction_pool.go:132" tag=txpool
INFO[0005] Block a7bb83297a731dbdb11e279e50e13138bc274b306b2ac10010e05f7895cd7050 connects to main chain  source="txpool/transaction_pool.go:132" tag=txpool
ERRO[0005] Failed to set tail block. Hash: a7bb83297a731dbdb11e279e50e13138bc274b306b2ac10010e05f7895cd7050, Height: 219, Err: Filter can only be added in chain sequence  source="chain/blockchain.go:383" tag=chain
ERRO[0005] Filter can only be added in chain sequence    source="chain/blockchain.go:298" tag=chain
panic: Filter can only be added in chain sequence

goroutine 313 [running]:
github.com/BOXFoundation/boxd/blocksync.(*SyncManager).onBlocksResponse.func1(0xc010a87240, 0xc00034c0f0)
	/Users/xiaocong/.gvm/pkgsets/go1.11/global/src/github.com/BOXFoundation/boxd/blocksync/manager.go:671 +0x1a9
created by github.com/BOXFoundation/boxd/blocksync.(*SyncManager).onBlocksResponse
	/Users/xiaocong/.gvm/pkgsets/go1.11/global/src/github.com/BOXFoundation/boxd/blocksync/manager.go:662 +0x2b9
1```

**Comment by jiaruijiang** [comment]
fixed
