### ISSUE TITLE
rpc error: code = Unknown desc = Not enough balance

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#167]
```
INFO[0038] --- PASS: prepareUTXOs                        source="tests/test_tx.go:182" tag=tests
INFO[0038] balance for addr b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv is 171147735  source="tests/test_tx.go:52" tag=tests
INFO[0038] === RUN   txRepeatTest                        source="tests/test_tx.go:186" tag=tests
INFO[0039] fromAddr[b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv] balance: 171147735, utox count: 101, max: 48538701, min: 633304  source="tests/test_tx.go:199" tag=tests
INFO[0039] toAddr[b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN] balance: 42629432  source="tests/test_tx.go:202" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0039] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
INFO[0040] sent 645543 from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv to b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN on peer 127.0.0.1:19191  source="tests/test_tx.go:207" tag=tests
PANI[0040] create transaction from b1fvc3pHNChbQFyZHQonEFcSh54CNWNbrgv, addr amont map map[b1Tos58FmFQ9LnoX9hiLvsTUJSCNcKz3WeN:645543], error: rpc error: code = Unknown desc = Not enough balance  source="tests/boxutil.go:140" tag=tests
INFO[0040] remove 10 keystore files                      source="tests/util.go:164" tag=tests
INFO[0040] process[26242] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] process[26241] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] process[26244] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] process[26243] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] process[26240] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] process[26239] exit status 0                  source="tests/util.go:67" tag=tests
INFO[0040] clean ./.devconfig/ws1 database and logs      source="tests/util.go:129" tag=tests
INFO[0040] clean ./.devconfig/ws2 database and logs      source="tests/util.go:129" tag=tests
INFO[0040] clean ./.devconfig/ws3 database and logs      source="tests/util.go:129" tag=tests
INFO[0040] clean ./.devconfig/ws4 database and logs      source="tests/util.go:129" tag=tests
INFO[0040] clean ./.devconfig/ws5 database and logs      source="tests/util.go:129" tag=tests
INFO[0040] clean ./.devconfig/ws6 database and logs      source="tests/util.go:129" tag=tests
panic: (*logrus.Entry) (0x18d6b20,0xc020a45800)

goroutine 1 [running]:
github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000e4820, 0xc020a4f4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus/entry.go:138 +0x29c
github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc020a45740, 0xc0000d5a50, 0x1, 0x1)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus/entry.go:206 +0xb8
github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus.(*Entry).Panicf(0xc020a45740, 0x19117d3, 0x38, 0xc020a4f470, 0x3, 0x3)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/vendor/github.com/sirupsen/logrus/entry.go:254 +0xed
github.com/BOXFoundation/boxd/log/logrus.(*logrusLogger).Panicf(0xc00000d940, 0x19117d3, 0x38, 0xc020a4f470, 0x3, 0x3)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/log/logrus/logrus.go:126 +0x6b
main.execTx(0xc02192de90, 0xc0004bcc00, 0x23, 0xc02128d5d0, 0x1, 0x1, 0xc0000d5cb0, 0x1, 0x1, 0x18f0d93, ...)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/tests/boxutil.go:140 +0x6a5
main.txRepeatTest(0xc0004bcc00, 0x23, 0xc0000cad50, 0x23, 0x18f0d93, 0xf, 0x64)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/tests/test_tx.go:209 +0x632
main.(*txTest).testTx(0xc00027e040)
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/tests/test_tx.go:55 +0x3c5
main.main()
	/Users/jerrypeen/go/src/github.com/BOXFoundation/boxd/tests/main.go:89 +0x687
```

**Comment by jiaruijiang** [comment]
Transaction generation logic changed since commit f57f55468854146d279ef17024390521117b0e7c
