### ISSUE TITLE
processing block with 38 tx cost 3s and panic on "Trying to unspend non-existing spent output"

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#217]
on n2:
```
time="2018-12-03T15:40:35+08:00" level=info msg="Finish packing txs. Hash: b329c34cfd6b30b181c11ede80817aac878e37bcd3221c65bbc7e979daa42990, Height: 428, TxsNum: 38" source="dpos/dpos.go:347" tag=dpos
...
...
time="2018-12-03T15:40:38+08:00" level=debug msg="UTXO: apply block with 38 transactions" source="chain/utxoset.go:164" tag=chain
time="2018-12-03T15:40:38+08:00" level=debug msg="Broadcast New Block. Hash: b329c34cfd6b30b181c11ede80817aac878e37bcd3221c65bbc7e979daa42990 Height: 428" source="chain/blockchain.go:282" tag=chain
```

```
time="2018-12-03T15:40:46+08:00" level=info msg="Prepare to process block. Hash: c4ce03cfcbbd9bea3fe3fd01162aef4bfd303ee7dad8e78ee2b4da6505f19f2c, Height: 429" source="chain/blockchain.go:236" tag=chain
time="2018-12-03T15:40:46+08:00" level=info msg="REORGANIZE: Block c4ce03cfcbbd9bea3fe3fd01162aef4bfd303ee7dad8e78ee2b4da6505f19f2c is causing a reorganization." source="chain/blockchain.go:358" tag=chain
time="2018-12-03T15:40:46+08:00" level=panic msg="Trying to unspend non-existing spent output {ab0dcfd5c858f6b38190f3a1a11182a4634e0dd2387676e0d801c4d96edf3cac 1}" source="chain/utxoset.go:187" tag=chain
panic: (*logrus.Entry) (0xe3dee0,0xc01c6cfda0)

goroutine 99 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000e4820, 0xc0107d4ed0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:138 +0x29c
github.com/sirupsen/logrus.(*Entry).Panic(0xc01c6cfd40, 0xc01cab5798, 0x1, 0x1)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:206 +0xb8
github.com/sirupsen/logrus.(*Entry).Panicf(0xc01c6cfd40, 0xe7984c, 0x2e, 0xc016dcdea0, 0x1, 0x1)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:254 +0xed
github.com/BOXFoundation/boxd/log/logrus.(*logrusLogger).Panicf(0xc000499c20, 0xe7984c, 0x2e, 0xc016dcdea0, 0x1, 0x1)
        /box/app/boxd/log/logrus/logrus.go:126 +0x6b
github.com/BOXFoundation/boxd/core/chain.(*UtxoSet).RevertTx(0xc01cab5970, 0xc011ae9f20, 0x18b12c52000001ac, 0xc01d862a80, 0x0)
        /box/app/boxd/core/chain/utxoset.go:187 +0x297
github.com/BOXFoundation/boxd/core/chain.(*UtxoSet).RevertBlock(0xc01cab5970, 0xc0169f90e0, 0x1081c60, 0xc00020a840)
        /box/app/boxd/core/chain/utxoset.go:203 +0x73
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).revertBlock(0xc0002dc400, 0xc0169f90e0, 0x107e860, 0xc01d676d00, 0x1, 0x1)
        /box/app/boxd/core/chain/blockchain.go:531 +0x92
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).reorganize(0xc0002dc400, 0xc011c87d60, 0x107e860, 0xc01d676d00, 0x1, 0x1)
        /box/app/boxd/core/chain/blockchain.go:611 +0xc9
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).tryAcceptBlock(0xc0002dc400, 0xc011c87d60, 0x0, 0x0)
        /box/app/boxd/core/chain/blockchain.go:359 +0x63a
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).ProcessBlock(0xc0002dc400, 0xc011c87d60, 0x100, 0xc010c1f470, 0x26, 0x0, 0x0)
        /box/app/boxd/core/chain/blockchain.go:271 +0x806
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).processBlockMsg(0xc0002dc400, 0x1078120, 0xc01d447f20, 0x0, 0x1)
        /box/app/boxd/core/chain/blockchain.go:221 +0x11e
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).loop(0xc0002dc400, 0x1081de0, 0xc000210960)
        /box/app/boxd/core/chain/blockchain.go:183 +0x371
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).loop-fm(0x1081de0, 0xc000210960)
        /box/app/boxd/core/chain/blockchain.go:147 +0x3e
github.com/jbenet/goprocess.(*process).Go.func1(0xc000220630, 0xc000210960, 0xc0002109c0)
        /home/app/go/pkg/mod/github.com/jbenet/goprocess@v0.0.0-20160826012719-b497e2f366b8/impl-mutex.go:112 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
        /home/app/go/pkg/mod/github.com/jbenet/goprocess@v0.0.0-20160826012719-b497e2f366b8/impl-mutex.go:111 +0x1f5
time="2018-12-03T15:40:46+08:00" level=info msg="Creating rocksdb at /box/n2/database/testnet" source="rocksdb/db.go:35" tag=rocksdb
```

**Comment by LeonLi000** [comment]
A &rarr; B &rarr; C &rarr; D &rarr; E
A &rarr; B1 &rarr; C &rarr; D &rarr; E1
If B1 and E1  both have block revert, and E1 refers to B1's vin, and the above bug will appear.
This is because when the block reverts, the database rolls back the data but the cache does not roll back the data.
