### ISSUE TITLE
token.go panic

### ISSUE THREAD

**Issue by jiaruijiang** [BOXFoundation/boxd#222]
https://github.com/BOXFoundation/boxd/blob/693e4a6b9ae79b734fa3f39576148e79b2af9b97/script/token.go#L170

```
panic: runtime error: slice bounds out of range

goroutine 229 [running]:
github.com/BOXFoundation/boxd/script.(*Script).IsTokenIssue(0xc0005cf810, 0xc0109a6bc0)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/script/token.go:170 +0xb8a
github.com/BOXFoundation/boxd/rpc/server.convertVout(0xc0109b0380, 0xc0006165c0, 0x3c, 0x3c)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/server/rpc_webapi.go:322 +0xf4
github.com/BOXFoundation/boxd/rpc/server.(*webapiServer).convertTransaction(0xc0002161c0, 0xc00057dda0, 0xc0001fcf90, 0x0, 0x0, 0x0)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/server/rpc_webapi.go:605 +0x16d
github.com/BOXFoundation/boxd/rpc/server.(*webapiServer).convertTransactionInfos(0xc0002161c0, 0xc0000d4670, 0x1, 0x1, 0xc0001fcf90, 0x0, 0x0, 0x464d3e4, 0xc0000e9860, 0xc0001181c0)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/server/rpc_webapi.go:577 +0x88
github.com/BOXFoundation/boxd/rpc/server.(*webapiServer).convertBlock(0xc0002161c0, 0xc0000e9860, 0xed0c29466ea8917d, 0xbba6586c4973383, 0x286845d9b7580cac)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/server/rpc_webapi.go:677 +0x10d
github.com/BOXFoundation/boxd/rpc/server.(*webapiServer).GetBlock(0xc0002161c0, 0x4cb39e0, 0xc0001fcf00, 0xc010a077f0, 0xc0002161c0, 0xc0001fce70, 0x49702e0)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/server/rpc_webapi.go:453 +0xd7
github.com/BOXFoundation/boxd/rpc/pb._WebApi_GetBlock_Handler(0x4a47060, 0xc0002161c0, 0x4cb39e0, 0xc0001fcf00, 0xc00014d810, 0x0, 0x0, 0x0, 0x46e13df, 0xc0001d2540)
	/Users/jiarui.jiang/go/src/github.com/BOXFoundation/boxd/rpc/pb/web.pb.go:1927 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00066f200, 0x4cb8660, 0xc000604900, 0xc00064e400, 0xc0001d3b60, 0x5422dd8, 0x0, 0x0, 0x0)
	/Users/jiarui.jiang/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:982 +0x4cd
google.golang.org/grpc.(*Server).handleStream(0xc00066f200, 0x4cb8660, 0xc000604900, 0xc00064e400, 0x0)
	/Users/jiarui.jiang/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1208 +0x1308
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036100, 0xc00066f200, 0x4cb8660, 0xc000604900, 0xc00064e400)
	/Users/jiarui.jiang/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:686 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/jiarui.jiang/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:684 +0xa1
```

**Comment by xhliu** [comment]
Did u create a split address? Can u help verify?  This is the only case I can think of that can cause this error. If not, we have some other bugs.
