### ISSUE TITLE
Trying to unspend non-existing spent output

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#290]
```
time="2019-06-14T15:31:36+08:00" level=info msg="Prepare to process block. Hash: 4dcfda914c736c309f32ee49fb37d27145b77238d34c1fd0096f8075a5526522, Height: 185459" source="chain/blockchain.go:426" tag=chain
time="2019-06-14T15:31:36+08:00" level=warning msg="REORGANIZE: Block 4dcfda914c736c309f32ee49fb37d27145b77238d34c1fd0096f8075a5526522 is causing a reorganization." source="chain/blockchain.go:570" tag=chain
time="2019-06-14T15:31:36+08:00" level=info msg="Try to disconnect block from main chain. Hash: d313672f7262234f7b4f7d69cd0f3e1597e604521dd35f9b4ab959b33e225847 Height: 185458" source="chain/blockchain.go:1128" tag=chain
time="2019-06-14T15:31:36+08:00" level=error msg="Failed to load block info by txhash. Err: %vEOF" source="chain/utxoset.go:336" tag=chain
time="2019-06-14T15:31:36+08:00" level=panic msg="Trying to unspend non-existing spent output {Hash: 05aaf4d82f9467f89032d8408f22dd7e2451134d24a968f9d0b6fd4b05fd41cb, Index: 0}" source="chain/utxoset.go:337" tag=chain
panic: (*logrus.Entry) (0xfc8f60,0xc01157a2a0)

goroutine 129 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000d2820, 0xc004220b70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:138 +0x29c
github.com/sirupsen/logrus.(*Entry).Panic(0xc01157a000, 0xc004b2d4f8, 0x1, 0x1)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:206 +0xb8
github.com/sirupsen/logrus.(*Entry).Panicf(0xc01157a000, 0x100cc07, 0x2e, 0xc00449c7a0, 0x1, 0x1)
        /home/app/go/pkg/mod/github.com/sirupsen/logrus@v1.1.1/entry.go:254 +0xed
github.com/BOXFoundation/boxd/log/logrus.(*logrusLogger).Panicf(0xc000453d60, 0x100cc07, 0x2e, 0xc00449c7a0, 0x1, 0x1)
        /box/app/boxd/log/logrus/logrus.go:126 +0x6b
github.com/BOXFoundation/boxd/core/chain.(*UtxoSet).RevertTx(0xc004b2d8f8, 0xc0016e9020, 0xc0001bea80, 0x3f9ad9561, 0x0)
        /box/app/boxd/core/chain/utxoset.go:337 +0x4d4
github.com/BOXFoundation/boxd/core/chain.(*UtxoSet).RevertBlock(0xc004b2d8f8, 0xc0016e8c60, 0xc0001bea80, 0x1273080, 0xc000260280)
        /box/app/boxd/core/chain/utxoset.go:361 +0x10f
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).tryDisConnectBlockFromMainChain(0xc0001bea80, 0xc00029b200, 0x0, 0x0)
        /box/app/boxd/core/chain/blockchain.go:1146 +0x361
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).reorganize(0xc0001bea80, 0xc0125f0360, 0xc000352240, 0x26, 0x1, 0x1)
        /box/app/boxd/core/chain/blockchain.go:1103 +0x3ae
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).tryAcceptBlock(0xc0001bea80, 0xc0125f0360, 0xc000352240, 0x26, 0x4df21fc4f5be9848, 0x1)
        /box/app/boxd/core/chain/blockchain.go:572 +0x866
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).ProcessBlock(0xc0001bea80, 0xc0125f0360, 0x2, 0xc000352240, 0x26, 0x0, 0x0)
        /box/app/boxd/core/chain/blockchain.go:469 +0x6ec
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).processBlockMsg(0xc0001bea80, 0x1265040, 0xc011f7a2e0, 0x0, 0x1)
        /box/app/boxd/core/chain/blockchain.go:406 +0x119
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).loop(0xc0001bea80, 0x1270ba0, 0xc0001db1a0)
        /box/app/boxd/core/chain/blockchain.go:240 +0x39e
github.com/BOXFoundation/boxd/core/chain.(*BlockChain).loop-fm(0x1270ba0, 0xc0001db1a0)
        /box/app/boxd/core/chain/blockchain.go:179 +0x3e
github.com/jbenet/goprocess.(*process).Go.func1(0xc0001e6c70, 0xc0001db1a0, 0xc0001db200)
        /home/app/go/pkg/mod/github.com/jbenet/goprocess@v0.0.0-20160826012719-b497e2f366b8/impl-mutex.go:112 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
        /home/app/go/pkg/mod/github.com/jbenet/goprocess@v0.0.0-20160826012719-b497e2f366b8/impl-mutex.go:111 +0x1f5
```

**Comment by LeonLi000** [comment]
Fixed in 9fe5cdf & b58e50c
