### ISSUE TITLE
Failed to accept the block into the main chain. Err: Referenced utxo does not exist

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#291]
```
time="2019-06-14T15:26:22+08:00" level=info msg="wait sync 33 blocks done" source="blocksync/manager.go:311" tag=blocksync
time="2019-06-14T15:26:22+08:00" level=info msg="has sync 33/33 blocks, current peer[12D3KooWQSaxCgbWakLcU69f4gmNFMszwhyHbwx4xPAhV7erDC2P]" source="blocksync/sync_server.go:308" tag=blocksync
time="2019-06-14T15:26:22+08:00" level=info msg="Prepare to process block. Hash: 38c73f0d2af6a7aeca4b474ffbfd06376ba75c9dabd5f685b158355f336b3956, Height: 185164" source="chain/blockchain.go:426" tag=chain
time="2019-06-14T15:26:22+08:00" level=info msg="complete to sync 33 blocks" source="blocksync/manager.go:318" tag=blocksync
time="2019-06-14T15:26:22+08:00" level=info msg="Try to connect block to main chain. Hash: 38c73f0d2af6a7aeca4b474ffbfd06376ba75c9dabd5f685b158355f336b3956, Height: 185164" source="chain/blockchain.go:666" tag=chain
time="2019-06-14T15:26:22+08:00" level=error msg="prev outpoint {Hash: 0337768d95517538f75b18306fd65d2c3ab4781a8d789eeba3addfd83982f212, Index: 0} in tx ef06149d23ba9931bfc3fd9dd489f2a8d6ce7d610dab735c553f71efc8c3a6cc vin[0] does not exist" source="chain/validate.go:249" tag=chain
time="2019-06-14T15:26:22+08:00" level=error msg="Failed to accept the block into the main chain. Err: Referenced utxo does not exist" source="chain/blockchain.go:470" tag=chain
panic: Referenced utxo does not exist

goroutine 93946 [running]:
github.com/BOXFoundation/boxd/blocksync.(*SyncManager).onBlocksResponse.func1(0xc015b6e880, 0xc0001340f0)
        /box/app/boxd/blocksync/sync_server.go:323 +0x2ce
created by github.com/BOXFoundation/boxd/blocksync.(*SyncManager).onBlocksResponse
        /box/app/boxd/blocksync/sync_server.go:312 +0x6cf
```

```
app@aliyun-boxd001:/box/app/logs$ echo '{"hash":"0337768d95517538f75b18306fd65d2c3ab4781a8d789eeba3addfd83982f212"}' | http POST http://127.0.0.1:19120/v1/tx/detail
HTTP/1.1 200 OK
Content-Length: 548
Content-Type: application/json
Date: Fri, 14 Jun 2019 08:01:41 GMT
Grpc-Metadata-Content-Type: application/grpc
Vary: Origin

{
    "block_height": 184591,
    "block_time": "1560496572",
    "code": 0,
    "detail": {
        "hash": "0337768d95517538f75b18306fd65d2c3ab4781a8d789eeba3addfd83982f212",
        "vin": [
            {
                "prev_out_detail": null,
                "prev_out_point": "",
                "script_sig": "",
                "sequence": 0
            }
        ],
        "vout": [
            {
                "addr": "b1jh8DSdB6kB7N7RanrudV1hzzMCCcoX6L7",
                "script_disasm": "OP_DUP OP_HASH160 ae3e96d008658db64dd4f8df2d736edbc6be1c31 OP_EQUALVERIFY OP_CHECKSIG",
                "script_pub_key": "76a914ae3e96d008658db64dd4f8df2d736edbc6be1c3188ac",
                "type": "pay_to_pubkey_hash",
                "value": "5001991893"
            }
        ]
    },
    "message": "",
    "status": "onchain",
    "version": 1
}

app@aliyun-boxd001:/box/app/logs$ echo '{"hash":"ef06149d23ba9931bfc3fd9dd489f2a8d6ce7d610dab735c553f71efc8c3a6cc"}' | http POST http://127.0.0.1:19120/v1/tx/detail
HTTP/1.1 200 OK
Content-Length: 1339
Content-Type: application/json
Date: Fri, 14 Jun 2019 08:02:51 GMT
Grpc-Metadata-Content-Type: application/grpc
Vary: Origin

{
    "block_height": 185164,
    "block_time": "1560497145",
    "code": 0,
    "detail": {
        "hash": "ef06149d23ba9931bfc3fd9dd489f2a8d6ce7d610dab735c553f71efc8c3a6cc",
        "vin": [
            {
                "prev_out_detail": {
                    "addr": "b1jh8DSdB6kB7N7RanrudV1hzzMCCcoX6L7",
                    "script_disasm": "OP_DUP OP_HASH160 ae3e96d008658db64dd4f8df2d736edbc6be1c31 OP_EQUALVERIFY OP_CHECKSIG",
                    "script_pub_key": "76a914ae3e96d008658db64dd4f8df2d736edbc6be1c3188ac",
                    "type": "pay_to_pubkey_hash",
                    "value": "5001991893"
                },
                "prev_out_point": "7FfG4QAbbRETFsZCdxadwzZ2NEHVz8bXqshcPhdmh3LeT2W5NP",
                "script_sig": "463044022041536ff9755f0aa686e5524f400d1e9bbf95f40793f19d28025e77356bf6cf080220235d62cc3b299916f0b805121ee7465708553cec2bacc77f98f622e5439ac3af21033de02b7317c84f14af7049854c4910f097d2edbd2fe367aa1205117ca4c19416",
                "sequence": 0
            }
        ],
        "vout": [
            {
                "addr": "b1pYVGCSH4StP61gdT5kwRArpUwutFA7FXj",
                "script_disasm": "OP_DUP OP_HASH160 e3750b4032310c73b8387bfab38c23d9f5e52c73 OP_EQUALVERIFY OP_CHECKSIG",
                "script_pub_key": "76a914e3750b4032310c73b8387bfab38c23d9f5e52c7388ac",
                "type": "pay_to_pubkey_hash",
                "value": "101000"
            },
            {
                "addr": "b1jh8DSdB6kB7N7RanrudV1hzzMCCcoX6L7",
                "script_disasm": "OP_DUP OP_HASH160 ae3e96d008658db64dd4f8df2d736edbc6be1c31 OP_EQUALVERIFY OP_CHECKSIG",
                "script_pub_key": "76a914ae3e96d008658db64dd4f8df2d736edbc6be1c3188ac",
                "type": "pay_to_pubkey_hash",
                "value": "5001890883"
            }
        ]
    },
    "message": "",
    "status": "onchain",
    "version": 0
}
```

**Comment by LeonLi000** [comment]
Fixed at 9fe5cdf36539e673fa6377c4f972a5fc35ee5378 & b58e50cab648def477d714bfa527ff7a8507c2a6
